### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by rcrespocano** [lmarti/nsgaiii#1]
Hi,

Can you help me with the following exception?

  File "/home/rcc/Dev/genretina/MoogaMetrics/nsga_iii_selection.py", line 208, in sel_nsga_iii
    selection += niching_select(fronts[limit], k - len(selection))
  File "/home/rcc/Dev/genretina/MoogaMetrics/nsga_iii_selection.py", line 158, in niching_select
    min_assoc_rp = min(reference_points, key=lambda rp: rp.associations_count)
ValueError: min() arg is an empty sequence

Thank you in advance.

Best regards.

**Comment by lmarti** [comment]
Can you please provide a test code that exposes the error. I have been trying to replicate it on my side but it always works. Thanks.

**Comment by rcrespocano** [comment]
It seems that the installation of the library has broken my DEAP framework. Now, the hypervol function doesn't works too.

How can I uninstall your library?

Thanks.

**Comment by lmarti** [comment]
About this last comment try: http://stackoverflow.com/questions/1550226/python-setup-py-uninstall
However, that thing you comment looks really awkward... wouldnt it be possible that you are mixing up something on your `import`s? Please, provide some code.

**Comment by rcrespocano** [comment]
My bad!

I've to use Python 2.7 and I've to add "`from __future__ import division`" to get correct reference points.

Sorry for the delay. I can only work on my PhD at night and weekends.

**Comment by lmarti** [comment]
well I have added a `from __future__ import division` to avoid this errors in the future.
